# Tarea Investigativa No. 3

## np.ndarray
***
Es un arreglo de objetos con múltiples dimensiones.
Dichos arreglos pueden entenderse como contenedores del mismo tamaño y tipo ordenados de una forma especifica.

Para declarar un array en Numpy se puede utilizar np.array() o np.ndarray(). A la función se le entrega una tupla o una lista para crear el array, para conocer la dimensión y la cantidad de elementos se utiliza la función shape.

In [35]:
import numpy as np
x = np.array([1,2,3,4,5,6])
print("Tipo de dato de x: " + str(type(x)))
print("Forma del array x: " + str(x.shape))
y = np.array([[1,2,3],[4,5,6]])
print("Tipo de dato de y: " + str(type(y)))
print("Forma del array y: " + str(y.shape))
z = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15,16],[17,18,19]],[[20,21,22],[23,24,25,26],[27,28,29,30]]])
print("Tipo de dato de z: " + str(type(z)))
print("Forma del array z: " + str(z.shape))

Tipo de dato de x: <class 'numpy.ndarray'>
Forma del array x: (6,)
Tipo de dato de y: <class 'numpy.ndarray'>
Forma del array y: (2, 3)
Tipo de dato de z: <class 'numpy.ndarray'>
Forma del array z: (3, 3)


## np.matrix
***
Es una subclase de arrays en Numpy.
La principal caracteristica de esta subclase es que las matrices son arreglos de dos dimensiones y sin importar las operaciones que se le aplique a la matriz (suma, resta, multiplicación, etc) el resultado será un arreglo de dos dimensiones.

In [36]:
a = np.matrix([[3,4,5],[1,2,7]])

In [37]:
print("Tipo de dato de a: " + str(type(a)))
print("Forma de a: " + str(a.shape))

Tipo de dato de a: <class 'numpy.matrix'>
Forma de a: (2, 3)


## Diferencias np.ndarray vs np.matrix
***
Aunque np.matrix sea una subclase de np.ndarray el resultado de algunas operaciones y métodos varian entre ellas.

Se declaran dos arreglos, uno del tipo numpy.ndarray y el otro del tipo numpy.matrix

<img src="x_array.png">
<img src="y_array.png">

In [38]:
x_array = np.array([[0.1,-1,25,10],[-12,6,4,0],[40,-0.5,9.5,77],[0,2,1.5,8]])
y_array = np.array([[20],[1.03],[5],[64]])

Al relizar una suma de entre dos np.array se considera que el resultado es el siguiente:

In [39]:
print(x_array + y_array)
print(x_array - y_array)

[[ 20.1   19.    45.    30.  ]
 [-10.97   7.03   5.03   1.03]
 [ 45.     4.5   14.5   82.  ]
 [ 64.    66.    65.5   72.  ]]
[[-19.9  -21.     5.   -10.  ]
 [-13.03   4.97   2.97  -1.03]
 [ 35.    -5.5    4.5   72.  ]
 [-64.   -62.   -62.5  -56.  ]]


Si se considera el procedimiento matemático para la suma o resta de matrices en algebra lineal esta restringida a matrices con la misma cantidad de filas y columnas, en el ejemplo anterior no fue el caso ya que python hizo el broadcasting de la matriz y_array para que pudiera ser operada con x_array.

In [40]:
print(x_array*y_array)

[[  2.   -20.   500.   200.  ]
 [-12.36   6.18   4.12   0.  ]
 [200.    -2.5   47.5  385.  ]
 [  0.   128.    96.   512.  ]]


En el ejemplo anterior con la multiplicación de ambos array si se toma en cuenta de nuevo la operatoria para multiplicar matrices con álgebra lineal el resultado debería ser una matriz de 4 filas y 1 columna, sin embargo lo que hizo python una vez más fue hacer el broadcasting de la matriz y_array para ser operada con x_array.
***
En los siguientes ejemplos se verá la suma, resta y multiplicación de los mismos arreglos pero esta vez declarados como np.matrix

In [41]:
x_matrix = np.matrix([[0.1,-1,25,10],[-12,6,4,0],[40,-0.5,9.5,77],[0,2,1.5,8]])
y_matrix = np.matrix([[20],[1.03],[5],[64]])

Se comprueba que ambos sean del tipo np.matrix

In [42]:
print(type(x_matrix))
print(type(y_matrix))

<class 'numpy.matrix'>
<class 'numpy.matrix'>


Para el caso de la suma o resta de estas dos matrices se observa que nos entrega un resultado igual al anterior, esto es porque una matriz en numpy es una subclase de np.array y también realiza broadcasting para que pueda ser operada.

In [43]:
print(x_matrix+y_matrix)

[[ 20.1   19.    45.    30.  ]
 [-10.97   7.03   5.03   1.03]
 [ 45.     4.5   14.5   82.  ]
 [ 64.    66.    65.5   72.  ]]


Ahora en el caso de realizar la multiplicación de matrices esta operación si se apega a los conceptos de algebra lineal entregando como resultado una matriz de 4 filas y 1 columna.

In [44]:
print(x_matrix*y_matrix)

[[ 765.97 ]
 [-213.82 ]
 [5774.985]
 [ 521.56 ]]


***
Para mencionar algunos atributos especiales que se pueden hacer con los arreglos de tipo np.matrix son:

* .getA1() Regresa un array de una dimensión con todos los elementos de la matriz dentro de este

In [45]:
x_matrix.getA1()

array([  0.1,  -1. ,  25. ,  10. , -12. ,   6. ,   4. ,   0. ,  40. ,
        -0.5,   9.5,  77. ,   0. ,   2. ,   1.5,   8. ])

* .getI() Regresa la inversa de una matriz

In [46]:
x_matrix.getI()

matrix([[-0.11838753,  1.13652031,  0.36625206, -3.37719167],
        [-0.24157051,  2.21907688,  0.66632699, -6.11143414],
        [ 0.00719317,  0.3309456 ,  0.0992657 , -0.9644238 ],
        [ 0.05904391, -0.61682152, -0.18519407,  1.833688  ]])

Sabemos que esto únicmaente pueden ser aplicados a objetos del tipo np.matrix porque si intentamos realizar lo mismo a objetos del tipo np.array se obtienen los siguientes errores:

In [47]:
x_array.getA1()

AttributeError: 'numpy.ndarray' object has no attribute 'getA1'

In [48]:
x_array.getI()

AttributeError: 'numpy.ndarray' object has no attribute 'getI'

***
Según la referencia consultada es recomendable dejar de implementar objetos de tipo np.matrix porque en futuras versiones de la librería se removerá.

## Bibliografía

***

1. The SciPy community. Numpy Reference - The N-dimensional array (ndarray) [[en línea]](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html#arithmetic-matrix-multiplication-and-comparison-operations) [Consulta: 18 de marzo de 2019]
2. The SciPy community. Numpy Reference - numpy.matrix [[en línea]](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html#numpy.matrix) [Consulta: 19 de marzo de 2019]
3. The SciPy community. Numpy Reference - Standard array subclasses [[en línea]](https://docs.scipy.org/doc/numpy/reference/arrays.classes.html#matrix-objects) [Consulta: 19 de marzo de 2019]
4. KLEIN, Bernd. Matrix Arithmetics under NumPy and Python [[en línea]](https://www.python-course.eu/matrix_arithmetic.php)
[Consulta: 18 de marzo de 2019]