# Multiplicación y aritmética matricial

In [2]:
import numpy as np



**Ejemplo en DS** : en inteligencia artificial y ML en la sub-rama "reinforcement learning" la "ecuacion de bellman" puede aplicarse de manera vectorizada a traves del operar vectores, matrices y escalares en una sola expresion.

<img src="https://rebornhugo.github.io/assets/images/post_images/%E5%BC%BA%E5%8C%96%E5%AD%A6%E4%B9%A02/bellman%20equation2.PNG">

* n = numero de estados del sistema.
* V(s) = vector que representa el valor esperado para cierto estado
* R = recompensa inmediata percibida por el agente al salir de cierto estado.(vector)
* P = matriz de transicion de la cadena de Markov sub-yacente.(matriz)
* γ = factor de descuento de recompensas futuras(escalar)

Calcular V(s) para el siguiente sistema aplicando la ecuación de bellman de manera vectorizada.

In [3]:
V = np.array([0,0,0]) # valor inicial de V(s)
R = np.array([10,2,5]) # vector de recompensas
P = np.array([[0.5,0.25,0.25],
              [0.2,0.40,0.40],
              [0.80,0.10,0.10]])  # matriz de transición
gamma = 0.99

V = R + (np.matmul(P, V))*gamma
print(V)

[10.  2.  5.]


### Ejercicio 

Implementar en una funcion neural_network(X) la red neuronal definida por la siguiente arquitectura:

<img src="http://i.imgur.com/UNlffE1.png">

Podemos validar si fue correctamente implementada si usamos como entrada el vector x=[1,1] . Debemos obtener el resultado mostrado en la imagen.

Una vez tenemos la implementacion correcta, cambiar la funcion de activacion de la capa de salida por la funcion de activacion ReLu(https://en.wikipedia.org/wiki/Rectifier_(neural_networks)):

<img src="https://cdn-images-1.medium.com/max/1600/1*DfMRHwxY1gyyDmrIAd-gjQ.png">

Luego evaluar la red neuronal sobre la matriz de datos X(de manera vectorizada):

### Respuesta:

Se comprueban los resultados para los valores de entrada de [1,1] para la red neuronal

In [4]:
def sigmoid(x): #convertir los valores de x al rango de 0 a 1
    
    return 1/(1+np.exp(-x))

In [5]:
X = np.array([1,1])

H_W = np.array([[0.712,0.355, 0.268],
                 [0.112,0.855,0.468]])
OL_W = np.array([[0.116],[0.329],[0.708]])

H1 = np.matmul(X,H_W)
print("Sin utilizar la función sigmoid para H1 y OL respectivamente: ")
print(H1)
OL = np.matmul(H1, OL_W)
print(OL)
print("====================== \n Utilizando la función sigmoid para H1 y OL respectivamente: ")
H1 = sigmoid(H1)
OL = sigmoid(np.matmul(H1, OL_W))
print(H1)
print(OL)

Sin utilizar la función sigmoid para H1 y OL respectivamente: 
[0.824 1.21  0.736]
[1.014762]
 Utilizando la función sigmoid para H1 y OL respectivamente: 
[0.69508477 0.77029895 0.67612055]
[0.69269553]


Se analiza para la red neuronal sobre el vector X requerido:

In [6]:
X = np.array([
    [0.1,2],
    [0.3,0.45],
    [5,9],
    [12,6],
    [7,5],
    [0.3,0.8],
    [12,5],
    [100,200],
    [7,8],
    [300,1500]])

print("Sin utilizar la función sigmoid el resultado de OL es: ")
OL = np.matmul(np.matmul(X,H_W), OL_W)
print(OL)
print("====================== \n Utilizando la función sigmoid el resultado de OL es: ")
OL = sigmoid(np.matmul(sigmoid(np.matmul(X,H_W)), OL_W))
print(OL)

Sin utilizar la función sigmoid el resultado de OL es: 
[[1.2901751e+00]
 [3.9827325e-01]
 [7.5763340e+00]
 [8.4233580e+00]
 [5.8520720e+00]
 [6.1724410e-01]
 [7.7977270e+00]
 [1.6403930e+02]
 [7.7289650e+00]
 [1.0551858e+03]]
 Utilizando la función sigmoid el resultado de OL es: 
[[0.70244573]
 [0.66259284]
 [0.75933678]
 [0.75973948]
 [0.75802295]
 [0.6739704 ]
 [0.75954693]
 [0.76005845]
 [0.75952743]
 [0.76005845]]


Realizando la función Rectificadora para el resultado anterior:

In [8]:
def relu(X):
    return np.maximum(X,0)

In [9]:
print("Aplicando la función rectificadora ReLU: ")
OL = relu(np.matmul(relu(np.matmul(X,H_W)), OL_W))
print(OL)

Aplicando la función rectificadora ReLU: 
[[1.2901751e+00]
 [3.9827325e-01]
 [7.5763340e+00]
 [8.4233580e+00]
 [5.8520720e+00]
 [6.1724410e-01]
 [7.7977270e+00]
 [1.6403930e+02]
 [7.7289650e+00]
 [1.0551858e+03]]
